const fs = require('fs');
const lines = [
  '@import "tailwindcss";',
  '',
  ':root {',
  '  --background: #ffffff;',
  '  --foreground: #111827;',
  '  --primary-400: #a97dc4;',
  '  --primary-500: #875b9a;',
  '  --primary-600: #6a437a;',
  '  --surface-1: #16141e;',
  '  --surface-2: #1e1b2a;',
  '  --surface-3: #26223a;',
  '  --border-subtle: rgba(135, 91, 154, 0.18);',
  '  --border-card: rgba(135, 91, 154, 0.30);',
  '  --text-primary: #f0eef5;',
  '  --text-secondary: #a89bb8;',
  '  --text-muted: #6b6080;',
  '}',
  '',
  '@theme inline {',
  '  --font-sans: var(--font-inter), var(--font-geist-sans), sans-serif;',
  '  --font-mono: var(--font-geist-mono);',
  '  --color-background: var(--background);',
  '  --color-foreground: var(--foreground);',
  '  --color-primary-400: var(--primary-400);',
  '  --color-primary-500: var(--primary-500);',
  '  --color-primary-600: var(--primary-600);',
  '  --color-surface-1: var(--surface-1);',
  '  --color-surface-2: var(--surface-2);',
  '  --color-surface-3: var(--surface-3);',
  '}',
  '',
  '*, *::before, *::after { box-sizing: border-box; }',
  '',
  'body {',
  '  background: var(--background);',
  '  color: var(--foreground);',
  '  font-family: var(--font-inter), sans-serif;',
  '  -webkit-font-smoothing: antialiased;',
  '}',
  '',
  '.listing-card {',
  '  background: linear-gradient(135deg, rgba(30,27,42,0.85) 0%, rgba(22,20,30,0.70) 100%);',
  '  backdrop-filter: blur(16px);',
  '  -webkit-backdrop-filter: blur(16px);',
  '  border: 1px solid var(--border-card);',
  '  border-radius: 16px;',
  '  transition: transform 220ms cubic-bezier(0.34,1.56,0.64,1), box-shadow 220ms ease, border-color 220ms ease;',
  '  will-change: transform;',
  '}',
  '',
  '.listing-card:hover {',
  '  transform: translateY(-6px) scale(1.01);',
  '  box-shadow: 0 20px 48px rgba(135,91,154,0.22), 0 4px 16px rgba(0,0,0,0.40);',
  '  border-color: var(--primary-400);',
  '}',
  '',
  '@keyframes shimmer {',
  '  0%   { background-position: -600px 0; }',
  '  100% { background-position:  600px 0; }',
  '}',
  '',
  '.skeleton {',
  '  border-radius: 8px;',
  '  background: linear-gradient(90deg, var(--surface-2) 25%, var(--surface-3) 50%, var(--surface-2) 75%);',
  '  background-size: 600px 100%;',
  '  animation: shimmer 1.4s infinite linear;',
  '}',
  '',
  '.category-badge {',
  '  display: inline-flex;',
  '  align-items: center;',
  '  gap: 4px;',
  '  padding: 3px 10px;',
  '  border-radius: 999px;',
  '  font-size: 0.70rem;',
  '  font-weight: 600;',
  '  letter-spacing: 0.06em;',
  '  text-transform: uppercase;',
  '  background: rgba(135,91,154,0.18);',
  '  color: var(--primary-400);',
  '  border: 1px solid rgba(135,91,154,0.30);',
  '}',
];
fs.writeFileSync('app/globals.css', lines.join('\n'), 'utf8');
console.log('globals.css written clean. Lines:', lines.length);
console.log('First line:', lines[0]);
console.log('No @import url() — Inter loaded via next/font in layout.tsx');
